### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by johno1985** [alphagov/calendars#113]
I am attempting to make an ajax call to:
https://www.gov.uk/bank-holidays.json
but I receive the following error:
XMLHttpRequest cannot load https://www.gov.uk/bank-holidays.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3030' is therefore not allowed access.

Is it possible to add a response header to allow cross domain request to this resource?

**Comment by tijmenb** [comment]
Hi @johno1985. I'm going to talk to some people and get back to you soon.

**Comment by johno1985** [comment]
Thanks @tijmenb

**Comment by johno1985** [comment]
Hi, is this change now live?

**Comment by tijmenb** [comment]
Hi @johno1985. We've just deployed this change. Hope it helps!

```
@tijmenb ~ $ curl -I https://www.gov.uk/bank-holidays.json?cachebust=123123
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
...
```

**Comment by johno1985** [comment]
Hi, there is still no Access Control header present

**Comment by johno1985** [comment]
![image](https://cloud.githubusercontent.com/assets/1640705/17707474/7cb230e0-63d8-11e6-9096-cef19d1d45f0.png)

**Comment by johno1985** [comment]
Hi @tijmenb, the header is still not present, could you please re-open?

**Comment by pmanrubia** [comment]
Hi @johno1985,
Could you please run ```curl -I https://www.gov.uk/bank-holidays.json``` in your terminal.
This is what I get:
```bash
$ curl -I https://www.gov.uk/bank-holidays.json
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
```

**Comment by johno1985** [comment]
Ah, yes, it's working now, maybe my browser had cached a stale response
